### ISSUE TITLE
TFC crashes on exit

### ISSUE THREAD

**Issue by ALTaleX531** [Satanarious/TranslucentFlyoutsConfig#47]
Here are the steps I took to reproduce the error

1. Switch to the "Global" tab.
2. Change the "Effect Type".
3. Click the "Apply" button.
4. Click the "Apply" button again.
5. Click the "x" button.

**Comment by TechySC23** [comment]
@Satanarious When I closed TFConfig for the first time (I installed TF v3.0.1 and uninstalled TF v3.0.0 Insider and TFC. Then I installed TFC again.) I got the error again 😔. But then I did some normal setting adjustments for TF for the menu. Then I closed it. Thankfully that time it didn't crash! 😄

**Comment by Satanarious** [comment]
Actually, I fixed it in code. That's why I closed the issue. I'll draft a new release with minor fixes in a minute.
