### ISSUE TITLE
some settings don't work

### ISSUE THREAD

**Issue by Au-angeloupali** [Satanarious/TranslucentFlyoutsConfig#49]
I installed correctly, but some options are not working.
my system is a 23H2 Build 22631.3296

![image](https://github.com/Satanarious/TranslucentFlyoutsConfig/assets/118266752/16f83fca-4d63-4723-a525-9c2c111af91c)

the version of traslucent flayout is v3.0.1

I also tried all the "theme colorization" options but they are never accepted,

**Comment by TechySC23** [comment]
Look those options don't work. They just don't work. I don't know why. The dev of this repo has said that he is working on fixing this.

**Comment by Satanarious** [comment]
What version of Translucent Flyout are you on? There was a problem with reading registry values in v3.0.0. But they were fixed in v3.0.1.
If you want to see color changes on the hovered item, you are altering the wrong setting. Make changes in the `Hot` section. Keep `Enable Theme Colorization` as `No` if you want to alter colors and keep it as `Yes` if you want your current windows accent color.

To be honest, I don't know what focusing even does.

![image](https://github.com/Satanarious/TranslucentFlyoutsConfig/assets/42642682/2e085f92-38d8-42eb-b0cd-7a56dc29fd47)

**Comment by Satanarious** [comment]
> Look those options don't work. They just don't work. I don't know why. The dev of this repo has said that he is working on fixing this.

I'm not working on fixing this, this already works. Registry values were not read properly on TF v3.0.0, that's why a newer version, v3.0.1 was released which fixed the problem, and every old setting in TFC works.

**Comment by Au-angeloupali** [comment]
@Satanarious thank you very much! but I did as you suggested before and installed version 3.0.1 and now it works correctly.

Do you know if there is a way to set not only the HOT color but also the color of the writing inside and also of the non-enabled items?

![image](https://github.com/Satanarious/TranslucentFlyoutsConfig/assets/118266752/4b651d92-5802-48b5-a236-d73d0a46c43a)

the inactive entries are not readable on some backgrounds and it would be convenient to darken them, otherwise I would also make the writing in the HOT white as in the example below

![image](https://github.com/Satanarious/TranslucentFlyoutsConfig/assets/118266752/f29eb27f-4cda-4c02-b008-fa6db407d97c)

**Comment by Au-angeloupali** [comment]
Unfortunately, however, the Photoshop menus have remained the same...

![image](https://github.com/Satanarious/TranslucentFlyoutsConfig/assets/118266752/487e4531-06c9-4e49-b1f3-82d80c645c31)

**Comment by Satanarious** [comment]
You'll need to talk to TF's maintainer regarding that. You might want to continue about these [here](https://github.com/ALTaleX531/TranslucentFlyouts/issues/117).

Closing this.

**Comment by TechySC23** [comment]
@Satanarious Actually that was the old comment, today I installed v3.0.1 of TF and works.

>Keep Enable Theme Colorization as No if you want to alter colors and keep it as Yes if you want your current windows accent color.
Thanks for the tip BTW! 😄
