### ISSUE TITLE
When v1.4 is coming?

### ISSUE THREAD

**Issue by TechySC23** [Satanarious/TranslucentFlyoutsConfig#52]
Just wanted to know about the next release. Even estimate is 👌

**Comment by Satanarious** [comment]
I haven't started working on it yet. My main focus was fixing the old settings and the crash problem.Now that, that is done, I have another project that I'm working on. I'll start soon. Cannot promise a date or time. 
Also TF v3.0.0+ doesn't have many visual changes. What changes are you looking forward to? Let me know and I'll see if I can add them sooner.

**Comment by TechySC23** [comment]
> My main focus was fixing the old settings and the crash problem.

Completely okay. The main priority was to fix that.

**Comment by Satanarious** [comment]
You can open a discussion if you have any other questions. Closing this
