### ISSUE TITLE
External Function(Download and Install) not working

### ISSUE THREAD

**Issue by Dhyfer1** [Satanarious/TranslucentFlyoutsConfig#53]
As mentioned in the title

So we have two installation options: Recommended and Manual, of these two only the Manual option works without problem. The Recommended option is not downloading any files because when I click on the Download and Install button in External Functions, TranslucentFlyoutsConfig stays on screen for a few seconds and closes by itself.

When I open TranslucentFlyoutsConfig again, there is no path set in the Installation Location field, so it is not downloading any files. Only the Manual installation option works.

I hope this bug will be fixed in the next version.

Thanks.

**Comment by Dhyfer1** [comment]
Thanks for the update, but this new version 1.4.0 doesn't let me open TranslucentFlyoutsConfig.exe

When I want to open the executable, what you can see in the image appears, and the same happens when I run it as administrator. 

![2024-03-25_211454](https://github.com/Satanarious/TranslucentFlyoutsConfig/assets/50301201/1a2c44ed-4a3e-4f8f-a34c-4ed6d28fe9f4)

**Comment by Satanarious** [comment]
I will look into this. Thanks for the screenshot.

**Comment by Dhyfer1** [comment]
You're welcome. I hope you can fix it

**Comment by Satanarious** [comment]
Actually it's something I missed during testing because I already have the required registry keys created.

**Comment by Dhyfer1** [comment]
Ok. I hope the next version can use TranslucentflyoutsConfig, in the meantime I will use the previous version

**Comment by Satanarious** [comment]
Something's wrong with github's upload. It's quite slow. I have fixed the error. Expect a re-release soon

**Comment by Satanarious** [comment]
You can download the re-release it has been uploaded

**Comment by Dhyfer1** [comment]
Thank you very much for fixing it. The executable can now be opened and the Recommended installation option now works. 😊

**Comment by Satanarious** [comment]
Well, thank you for the crash report. Have a good day.
