### ISSUE TITLE
+ Text Color -> Menu items

### ISSUE THREAD

**Issue by Au-angeloupali** [Satanarious/TranslucentFlyoutsConfig#62]
i'he seen that in the last version now you can set the Tooltip text color, ther's the possibility in the next version to set the color also in the text menu item in the various state (hot - inactive - selectable - ...)
thanks Angelo.

**Comment by Satanarious** [comment]
My application is just the front-end, all the heavy lifting is done by [Translucent Flyouts](https://github.com/ALTaleX531/TranslucentFlyouts). Create an issue there.
