### ISSUE TITLE
Process name doesn't stick after reopening "Disabled List" window

### ISSUE THREAD

**Issue by 03302024** [Satanarious/TranslucentFlyoutsConfig#68]
I wanted to add "explorer.exe" to the global "Disabled List", but the process name doesn't stick after reopening the list window.

**Comment by Satanarious** [comment]
Make sure you follow these steps:
- Enter the process name.
- Press ⏎enter(return)
- Click on apply.

If you do these, it still won't work. Let me know.

**Comment by Satanarious** [comment]
I will look into it. I donno how I didn't notice it. Thanks for reporting this. I will fix it in the next release.

**Comment by 03302024** [comment]
Thank you for looking into this.

While you are at this, please add an "Add" button there, to be used instead of pressing "Enter" on the keyboard.

**Comment by Satanarious** [comment]
Will do. Thank you.

**Comment by Satanarious** [comment]
Would you please create a new issue for the 'Add' button?

**Comment by 03302024** [comment]
Done.

**Comment by Satanarious** [comment]
Fixed in #71 : The next release will have it working and will also contain instructions to revert the repercussions of this one.

**Comment by 03302024** [comment]
Thank you. It works.
